name = "semantics"
version = "0.1.0"
defaultTargets = ["semantics"]

[[lean_lib]]
name = "Semantics"

[[lean_exe]]
name = "semantics"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"